# Generated by Django 3.2 on 2021-10-13 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColdStart',
            fields=[
                ('no', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='default', max_length=20)),
                ('selected_image', models.CharField(default='default', max_length=50)),
                ('coldstart', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='GanRequest',
            fields=[
                ('no', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('user_image', models.ImageField(default='default.jpeg', upload_to='media')),
                ('hair_color', models.CharField(default='default', max_length=20)),
                ('hair_style', models.CharField(default='default', max_length=50)),
                ('gan_image', models.ImageField(default='default.jpeg', upload_to='media')),
                ('gan_image_base64', models.TextField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('no', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='0', max_length=10)),
                ('user_num', models.IntegerField(default=-1)),
                ('last_recommend', models.JSONField(default=dict)),
                ('isexist', models.BooleanField(default=False)),
                ('isrecommended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PersonTest',
            fields=[
                ('no', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='0', max_length=10)),
                ('user_num', models.IntegerField(default=-1)),
                ('last_recommend', models.JSONField(default=dict)),
                ('isexist', models.BooleanField(default=False)),
                ('isrecommended', models.BooleanField(default=False)),
                ('hair_texture', models.TextField(default='default')),
                ('hair_volume', models.TextField(default='default')),
                ('hair_condition', models.TextField(default='default')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendResult',
            fields=[
                ('no', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('image_input', models.TextField(default='default')),
                ('face', models.JSONField(default=dict)),
                ('face_info', models.JSONField(default=dict)),
                ('color_info', models.JSONField(default=dict)),
                ('recommend_result_hairList_json', models.JSONField(default=dict)),
                ('hair_texture', models.TextField(default='default')),
                ('hair_volume', models.TextField(default='default')),
                ('hair_condition', models.TextField(default='default')),
                ('date', models.TextField(default='default')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommend_result', to='myapp.person')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendTest',
            fields=[
                ('no', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('person', models.IntegerField(default=-1)),
                ('image_input', models.TextField(default='default')),
                ('face', models.JSONField(default=dict)),
                ('face_info', models.JSONField(default=dict)),
                ('color_info', models.JSONField(default=dict)),
                ('hair_texture', models.TextField(default='default')),
                ('hair_volume', models.TextField(default='default')),
                ('hair_condition', models.TextField(default='default')),
                ('date', models.TextField(default='default')),
                ('recommend_result_hairList_json', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SconData',
            fields=[
                ('version', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('personalcolor_info', models.JSONField(default=dict)),
                ('recommend_hair_domain', models.JSONField(default=dict)),
                ('face_shape_info', models.JSONField(default=dict)),
                ('face_ratio_info', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('version', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('userid_json', models.JSONField(default=dict)),
                ('nofuser', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='SimulationStyleList',
            fields=[
                ('no', models.AutoField(db_column='NO', primary_key=True, serialize=False)),
                ('possible_style_img', models.ImageField(default='default.jpeg', upload_to='media')),
                ('simulation_style_img', models.ImageField(default='default.jpeg', upload_to='media')),
                ('recommend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_style_list', to='myapp.recommendresult')),
            ],
        ),
    ]
